/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'qianmin' at '16-9-6 下午5:21' with Gradle 2.14.1
 *
 * @author qianmin, @date 16-9-6 下午5:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
